remote_theme: just-the-docs/just-the-docs
title: Cloud-Native Entwicklung - Ãœbungen
color_scheme: dark

search_enabled: true
heading_anchors: true

# Footer content
footer_content: "Copyright &copy; 2025 AVD Academy"
